name: 'publish'

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: '🚀 node'
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry: 'registry.npmjs.org'
      - name: '📦 depen'
        run: npm install
      - name: '🛠️ build'
        run: npm run build
      - name: '📦 npm'
        run: npm version patch && npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
