name: 'publish'

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - name: '🚀 node'
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry: 'registry.npmjs.org'
      - name: '📦 npm'
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
